<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUYjMkgJ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUYjMkgJ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUYjMkgJ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUYjMkgJ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerUYjMkgJ\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'UYjMkgJ',
    'container.build_id' => '3c8a221d',
    'container.build_time' => 1541054208,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUYjMkgJ');
